/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataGalangDana(tabelGalangDana, "SELECT*FROM galangdana");
        mycode.tampilDataLSM(tabelLSM, "SELECT*FROM lsm");
        mycode.tampilDataDonasi(tabelDonasi, "SELECT*FROM donasi");
        mycode.tampilDataGaleri(tabelGaleri, "SELECT*FROM galeri");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlLsm = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNamaLSM = new javax.swing.JTextField();
        txtNoIzin = new javax.swing.JTextField();
        txtAlamatLSM = new javax.swing.JTextField();
        btnHpsLSM = new javax.swing.JButton();
        btnSmpnLSM = new javax.swing.JButton();
        btnUbhLSM = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtUserIdL = new javax.swing.JTextField();
        txtCariLSM = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelLSM = new javax.swing.JTable();
        txtPasswordLSM = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        pnlGalangDana = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDetailGD = new javax.swing.JTextField();
        txtIdGalangDana = new javax.swing.JTextField();
        txtFundraiserGD = new javax.swing.JTextField();
        txtUpdateInfoGD = new javax.swing.JTextField();
        txtCariGD = new javax.swing.JTextField();
        txtNipGD = new javax.swing.JTextField();
        btnHpsGd = new javax.swing.JButton();
        btnSmpnGd = new javax.swing.JButton();
        btnUbhGd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGalangDana = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtNoIzinGD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUserIdGD = new javax.swing.JTextField();
        pnlDonasi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDonasiUang = new javax.swing.JTextField();
        txtIdDonasi = new javax.swing.JTextField();
        txtDonasiSembako = new javax.swing.JTextField();
        txtDonasiBarang = new javax.swing.JTextField();
        txtCariDonasi = new javax.swing.JTextField();
        btnHpsDns = new javax.swing.JButton();
        btnSmpnDns = new javax.swing.JButton();
        btnUbhDns = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDonasi = new javax.swing.JTable();
        txtNipDns = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtUserIdDns = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtNoIzinDns = new javax.swing.JTextField();
        pnlGaleri = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelGaleri = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtFoto = new javax.swing.JTextField();
        txtIdGaleri = new javax.swing.JTextField();
        txtNoIzinGlr = new javax.swing.JTextField();
        txtKeteranganGlr = new javax.swing.JTextField();
        txtCariGlr = new javax.swing.JTextField();
        btnHpsGlr = new javax.swing.JButton();
        btnSmpnGlr = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        btnUbhGlr = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnLsm = new javax.swing.JButton();
        btnGalangDana = new javax.swing.JButton();
        btnDonasi = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnGaleri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlLsm.setBackground(new java.awt.Color(204, 255, 204));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Alamat LSM");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Nama LSM");

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("No Izin");

        txtNamaLSM.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaLSM.setForeground(new java.awt.Color(0, 0, 0));

        txtNoIzin.setBackground(new java.awt.Color(255, 255, 255));
        txtNoIzin.setForeground(new java.awt.Color(0, 0, 0));

        txtAlamatLSM.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatLSM.setForeground(new java.awt.Color(0, 0, 0));

        btnHpsLSM.setText("HAPUS");
        btnHpsLSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsLSMActionPerformed(evt);
            }
        });

        btnSmpnLSM.setText("SIMPAN");
        btnSmpnLSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnLSMActionPerformed(evt);
            }
        });

        btnUbhLSM.setText("UBAH");
        btnUbhLSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhLSMActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("User ID");

        txtUserIdL.setBackground(new java.awt.Color(255, 255, 255));
        txtUserIdL.setForeground(new java.awt.Color(0, 0, 0));

        txtCariLSM.setBackground(new java.awt.Color(255, 255, 255));
        txtCariLSM.setForeground(new java.awt.Color(0, 0, 0));
        txtCariLSM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariLSMKeyReleased(evt);
            }
        });

        tabelLSM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelLSM);

        txtPasswordLSM.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordLSM.setForeground(new java.awt.Color(0, 0, 0));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Password LSM");

        javax.swing.GroupLayout pnlLsmLayout = new javax.swing.GroupLayout(pnlLsm);
        pnlLsm.setLayout(pnlLsmLayout);
        pnlLsmLayout.setHorizontalGroup(
            pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLsmLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLsmLayout.createSequentialGroup()
                        .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLsmLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(txtNamaLSM, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLsmLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(90, 90, 90)
                                .addComponent(txtNoIzin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlLsmLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtPasswordLSM, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLsmLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(txtUserIdL, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLsmLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(48, 48, 48)
                                    .addComponent(txtAlamatLSM, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtCariLSM, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(25, 25, 25)
                        .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUbhLSM, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSmpnLSM, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHpsLSM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlLsmLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAlamatLSM, txtNamaLSM, txtNoIzin, txtPasswordLSM, txtUserIdL});

        pnlLsmLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsLSM, btnSmpnLSM, btnUbhLSM});

        pnlLsmLayout.setVerticalGroup(
            pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLsmLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNoIzin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(btnSmpnLSM))
                .addGap(12, 12, 12)
                .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNamaLSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(btnUbhLSM))
                .addGap(13, 13, 13)
                .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamatLSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(btnHpsLSM))
                .addGap(13, 13, 13)
                .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserIdL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(11, 11, 11)
                .addGroup(pnlLsmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordLSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(14, 14, 14)
                .addComponent(txtCariLSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        Content.add(pnlLsm, "card4");

        pnlGalangDana.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NIP");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fundraiser");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Update Info");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Detail");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID Galang Dana");

        txtDetailGD.setBackground(new java.awt.Color(255, 255, 255));
        txtDetailGD.setForeground(new java.awt.Color(0, 0, 0));

        txtIdGalangDana.setBackground(new java.awt.Color(255, 255, 255));
        txtIdGalangDana.setForeground(new java.awt.Color(0, 0, 0));

        txtFundraiserGD.setBackground(new java.awt.Color(255, 255, 255));
        txtFundraiserGD.setForeground(new java.awt.Color(0, 0, 0));

        txtUpdateInfoGD.setBackground(new java.awt.Color(255, 255, 255));
        txtUpdateInfoGD.setForeground(new java.awt.Color(0, 0, 0));

        txtCariGD.setBackground(new java.awt.Color(255, 255, 255));
        txtCariGD.setForeground(new java.awt.Color(0, 0, 0));
        txtCariGD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariGDKeyReleased(evt);
            }
        });

        txtNipGD.setBackground(new java.awt.Color(255, 255, 255));
        txtNipGD.setForeground(new java.awt.Color(0, 0, 0));

        btnHpsGd.setText("HAPUS");
        btnHpsGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsGdActionPerformed(evt);
            }
        });

        btnSmpnGd.setText("SIMPAN");
        btnSmpnGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnGdActionPerformed(evt);
            }
        });

        btnUbhGd.setText("UBAH");
        btnUbhGd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhGdActionPerformed(evt);
            }
        });

        tabelGalangDana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelGalangDana);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("No Izin");

        txtNoIzinGD.setBackground(new java.awt.Color(255, 255, 255));
        txtNoIzinGD.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("User ID");

        txtUserIdGD.setBackground(new java.awt.Color(255, 255, 255));
        txtUserIdGD.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlGalangDanaLayout = new javax.swing.GroupLayout(pnlGalangDana);
        pnlGalangDana.setLayout(pnlGalangDanaLayout);
        pnlGalangDanaLayout.setHorizontalGroup(
            pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(93, 93, 93)
                            .addComponent(txtDetailGD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnUbhGd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(47, 47, 47)
                            .addComponent(txtUpdateInfoGD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnHpsGd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(55, 55, 55)
                            .addComponent(txtFundraiserGD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(111, 111, 111)
                            .addComponent(txtNipGD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(81, 81, 81)
                            .addComponent(txtUserIdGD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(83, 83, 83)
                            .addComponent(txtNoIzinGD, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtCariGD, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtIdGalangDana, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSmpnGd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlGalangDanaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsGd, btnSmpnGd, btnUbhGd});

        pnlGalangDanaLayout.setVerticalGroup(
            pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGalangDanaLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtIdGalangDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSmpnGd))
                .addGap(13, 13, 13)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDetailGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbhGd))
                .addGap(13, 13, 13)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtUpdateInfoGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHpsGd))
                .addGap(13, 13, 13)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtFundraiserGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtNipGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserIdGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlGalangDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoIzinGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(txtCariGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Content.add(pnlGalangDana, "card3");

        pnlDonasi.setBackground(new java.awt.Color(204, 255, 204));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Donasi Sembako");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Donasi Barang");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Donasi Uang");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID Donasi");

        txtDonasiUang.setBackground(new java.awt.Color(255, 255, 255));
        txtDonasiUang.setForeground(new java.awt.Color(0, 0, 0));

        txtIdDonasi.setBackground(new java.awt.Color(255, 255, 255));
        txtIdDonasi.setForeground(new java.awt.Color(0, 0, 0));

        txtDonasiSembako.setBackground(new java.awt.Color(255, 255, 255));
        txtDonasiSembako.setForeground(new java.awt.Color(0, 0, 0));

        txtDonasiBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtDonasiBarang.setForeground(new java.awt.Color(0, 0, 0));

        txtCariDonasi.setBackground(new java.awt.Color(255, 255, 255));
        txtCariDonasi.setForeground(new java.awt.Color(0, 0, 0));
        txtCariDonasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariDonasiKeyReleased(evt);
            }
        });

        btnHpsDns.setText("HAPUS");
        btnHpsDns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsDnsActionPerformed(evt);
            }
        });

        btnSmpnDns.setText("SIMPAN");
        btnSmpnDns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnDnsActionPerformed(evt);
            }
        });

        btnUbhDns.setText("UBAH");
        btnUbhDns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhDnsActionPerformed(evt);
            }
        });

        tabelDonasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelDonasi);

        txtNipDns.setBackground(new java.awt.Color(255, 255, 255));
        txtNipDns.setForeground(new java.awt.Color(0, 0, 0));

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("NIP");

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("User ID");

        txtUserIdDns.setBackground(new java.awt.Color(255, 255, 255));
        txtUserIdDns.setForeground(new java.awt.Color(0, 0, 0));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("No Izin");

        txtNoIzinDns.setBackground(new java.awt.Color(255, 255, 255));
        txtNoIzinDns.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlDonasiLayout = new javax.swing.GroupLayout(pnlDonasi);
        pnlDonasi.setLayout(pnlDonasiLayout);
        pnlDonasiLayout.setHorizontalGroup(
            pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonasiLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlDonasiLayout.createSequentialGroup()
                        .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(31, 31, 31)
                        .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNipDns, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUserIdDns, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNoIzinDns, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDonasiSembako, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDonasiLayout.createSequentialGroup()
                                .addComponent(txtDonasiBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnHpsDns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlDonasiLayout.createSequentialGroup()
                                .addComponent(txtDonasiUang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnUbhDns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlDonasiLayout.createSequentialGroup()
                                .addComponent(txtIdDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnSmpnDns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlDonasiLayout.createSequentialGroup()
                        .addComponent(txtCariDonasi)
                        .addGap(108, 108, 108)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlDonasiLayout.setVerticalGroup(
            pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(btnSmpnDns))
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDonasiLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonasiUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbhDns)))
                    .addGroup(pnlDonasiLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDonasiLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnHpsDns))
                    .addGroup(pnlDonasiLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtDonasiBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonasiSembako, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNipDns, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(16, 16, 16)
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserIdDns, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlDonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtNoIzinDns, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(txtCariDonasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDonasiLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCariDonasi, txtDonasiBarang, txtDonasiSembako, txtDonasiUang, txtIdDonasi, txtNipDns, txtNoIzinDns, txtUserIdDns});

        Content.add(pnlDonasi, "card5");

        pnlGaleri.setBackground(new java.awt.Color(204, 255, 204));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Keterangan Galeri");

        tabelGaleri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelGaleri);

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Foto");

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID Galeri");

        txtFoto.setBackground(new java.awt.Color(255, 255, 255));
        txtFoto.setForeground(new java.awt.Color(0, 0, 0));

        txtIdGaleri.setBackground(new java.awt.Color(255, 255, 255));
        txtIdGaleri.setForeground(new java.awt.Color(0, 0, 0));

        txtNoIzinGlr.setBackground(new java.awt.Color(255, 255, 255));
        txtNoIzinGlr.setForeground(new java.awt.Color(0, 0, 0));

        txtKeteranganGlr.setBackground(new java.awt.Color(255, 255, 255));
        txtKeteranganGlr.setForeground(new java.awt.Color(0, 0, 0));

        txtCariGlr.setBackground(new java.awt.Color(255, 255, 255));
        txtCariGlr.setForeground(new java.awt.Color(0, 0, 0));
        txtCariGlr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariGlrKeyReleased(evt);
            }
        });

        btnHpsGlr.setText("HAPUS");
        btnHpsGlr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsGlrActionPerformed(evt);
            }
        });

        btnSmpnGlr.setText("SIMPAN");
        btnSmpnGlr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnGlrActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("No Izin Galeri");

        btnUbhGlr.setText("UBAH");
        btnUbhGlr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhGlrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGaleriLayout = new javax.swing.GroupLayout(pnlGaleri);
        pnlGaleri.setLayout(pnlGaleriLayout);
        pnlGaleriLayout.setHorizontalGroup(
            pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGaleriLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlGaleriLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txtIdGaleri, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSmpnGlr))
                    .addGroup(pnlGaleriLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(132, 132, 132)
                        .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnUbhGlr, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addGroup(pnlGaleriLayout.createSequentialGroup()
                        .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel32))
                        .addGap(25, 25, 25)
                        .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoIzinGlr, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlGaleriLayout.createSequentialGroup()
                                .addComponent(txtKeteranganGlr, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnHpsGlr, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtCariGlr, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlGaleriLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHpsGlr, btnSmpnGlr, btnUbhGlr});

        pnlGaleriLayout.setVerticalGroup(
            pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGaleriLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdGaleri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addComponent(btnSmpnGlr))
                .addGap(13, 13, 13)
                .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27))
                    .addComponent(btnUbhGlr))
                .addGap(13, 13, 13)
                .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKeteranganGlr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addComponent(btnHpsGlr))
                .addGap(18, 18, 18)
                .addGroup(pnlGaleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(txtNoIzinGlr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(txtCariGlr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pnlGaleriLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCariGlr, txtNoIzinGlr});

        Content.add(pnlGaleri, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SISTEM INFORMASI LSM");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(153, 255, 153));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnLsm.setBackground(new java.awt.Color(204, 255, 204));
        btnLsm.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnLsm.setForeground(new java.awt.Color(0, 0, 0));
        btnLsm.setText("LSM");
        btnLsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLsmActionPerformed(evt);
            }
        });

        btnGalangDana.setBackground(new java.awt.Color(204, 255, 204));
        btnGalangDana.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGalangDana.setForeground(new java.awt.Color(0, 0, 0));
        btnGalangDana.setText("GALANG DANA");
        btnGalangDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGalangDanaActionPerformed(evt);
            }
        });

        btnDonasi.setBackground(new java.awt.Color(204, 255, 204));
        btnDonasi.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDonasi.setForeground(new java.awt.Color(0, 0, 0));
        btnDonasi.setText("DONASI");
        btnDonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonasiActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnGaleri.setBackground(new java.awt.Color(204, 255, 204));
        btnGaleri.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGaleri.setForeground(new java.awt.Color(0, 0, 0));
        btnGaleri.setText("GALERI");
        btnGaleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaleriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGalangDana)
                    .addComponent(btnLsm, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDonasi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGaleri, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDonasi, btnGalangDana, btnGaleri, btnLsm});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLsm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGalangDana)
                .addGap(18, 18, 18)
                .addComponent(btnDonasi)
                .addGap(18, 18, 18)
                .addComponent(btnGaleri)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDonasi, btnGalangDana, btnGaleri, btnLsm});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnLsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLsmActionPerformed
        Content.removeAll(); 
        Content.add(pnlLsm);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnLsmActionPerformed

    private void btnGalangDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGalangDanaActionPerformed
        Content.removeAll(); 
        Content.add(pnlGalangDana);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnGalangDanaActionPerformed

    private void btnDonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonasiActionPerformed
        Content.removeAll(); 
        Content.add(pnlDonasi);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnDonasiActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnGaleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaleriActionPerformed
        Content.removeAll(); 
        Content.add(pnlGaleri);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnGaleriActionPerformed

    private void btnSmpnGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnGdActionPerformed
        try {
            if(txtIdGalangDana.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Galang Dana Belum Diisi");
                txtIdGalangDana.requestFocus();
            } else if(txtDetailGD.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Detail Belum Diisi");
                txtDetailGD.requestFocus();
            } else if(txtUpdateInfoGD.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Update Info Belum Diisi");
                txtUpdateInfoGD.requestFocus();
            } else if(txtFundraiserGD.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Fundraiser Belum Diisi");
                txtFundraiserGD.requestFocus();
            } else if(txtNipGD.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "NIP Belum Diisi");
                txtNipGD.requestFocus();
            } else if(txtUserIdGD.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "User ID Belum Diisi");
                txtUserIdGD.requestFocus();
            } else if(txtNoIzinGD.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Izin Belum Diisi");
                txtNoIzinGD.requestFocus();
            } else {
                mycode.simpanGalangDana02(txtIdGalangDana.getText(), txtDetailGD.getText(),
                                          txtUpdateInfoGD.getText(), txtFundraiserGD.getText(),
                                          txtNipGD.getText(), txtUserIdGD.getText(),
                                          txtNoIzinGD.getText());

                mycode.tampilDataGalangDana(tabelGalangDana, "SELECT*FROM GalangDana");

                if (mycode.duplikasi == true){
                    txtDetailGD.setText(mycode.CEK_DETAIL_GD);
                    txtUpdateInfoGD.setText(mycode.CEK_UPDATE_INFO_GD);
                    txtFundraiserGD.setText(mycode.CEK_FUNDRAISER_GD);
                    txtNipGD.setText(mycode.CEK_NIP_GD);
                    txtUserIdGD.setText(mycode.CEK_USER_ID_GD);
                    txtNoIzinGD.setText(mycode.CEK_NO_IZIN_GD);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnGdActionPerformed

    private void btnUbhGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhGdActionPerformed
        try {
            mycode.ubahGalangDana(txtIdGalangDana.getText(), txtFundraiserGD.getText(),
                                  txtUpdateInfoGD.getText(), txtCariGD.getText(),
                                  txtNipGD.getText(), txtUserIdGD.getText(),
                                  txtNoIzinGD.getText());

            // Refresh tabel
            mycode.tampilDataGalangDana(tabelGalangDana, "SELECT*FROM GalangDana");
        } catch (Exception e) {
    }
    }//GEN-LAST:event_btnUbhGdActionPerformed

    private void btnHpsGdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsGdActionPerformed
        try {
            mycode.hapusGalangDana(txtIdGalangDana.getText());
            mycode.tampilDataGalangDana(tabelGalangDana, "SELECT*FROM GalangDana");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsGdActionPerformed

    private void txtCariGDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariGDKeyReleased
        String c = txtCariGD.getText();
            String cari = "SELECT*FROM GalangDana WHERE ID_GalangDana LIKE '%"+c+"%'"+
                          "OR Detail LIKE '%"+c+"%' OR Update_Info LIKE '%"+c+"%'"+
                          "OR Fundraiser LIKE '%"+c+"%' OR NIP LIKE '%"+c+"%'"+
                          "OR User_id LIKE '%"+c+"%' OR No_Izin LIKE '%"+c+"%'";
            mycode.tampilDataGalangDana(tabelGalangDana, cari);
    }//GEN-LAST:event_txtCariGDKeyReleased

    private void btnUbhDnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhDnsActionPerformed
        try {
            mycode.ubahDonasi(txtIdDonasi.getText(), txtDonasiUang.getText(),
                              txtDonasiBarang.getText(), txtDonasiSembako.getText(),
                              txtNipDns.getText(), txtUserIdDns.getText(),
                              txtNoIzinDns.getText());

            mycode.tampilDataDonasi(tabelDonasi, "SELECT*FROM Donasi");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhDnsActionPerformed

    private void btnSmpnDnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnDnsActionPerformed
        try {
            if(txtIdDonasi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Donasi Belum Diisi");
                txtIdDonasi.requestFocus();
            } else if(txtDonasiUang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Donasi Uang Belum Diisi");
                txtDonasiUang.requestFocus();
            } else if(txtDonasiBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Donasi Barang Belum Diisi");
                txtDonasiBarang.requestFocus();
            } else if(txtDonasiSembako.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Donasi Sembako Belum Diisi");
                txtDonasiSembako.requestFocus();
            } else if(txtNipDns.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "NIP Belum Diisi");
                txtNipDns.requestFocus();
            } else if(txtUserIdDns.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "User ID Belum Diisi");
                txtUserIdDns.requestFocus();
            } else if(txtNoIzinDns.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Izin Belum Diisi");
                txtNoIzinDns.requestFocus();
            } else {
                mycode.simpanDonasi02(txtIdDonasi.getText(), txtDonasiUang.getText(),
                                      txtDonasiBarang.getText(), txtDonasiSembako.getText(),
                                      txtNipDns.getText(), txtUserIdDns.getText(),
                                      txtNoIzinDns.getText());

                mycode.tampilDataDonasi(tabelDonasi, "SELECT*FROM Donasi");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtDonasiUang.setText(mycode.CEK_DONASI_UANG);
                    txtDonasiBarang.setText(mycode.CEK_DONASI_BARANG);
                    txtDonasiSembako.setText(mycode.CEK_DONASI_SEMBAKO);
                    txtNipDns.setText(mycode.CEK_NIP_DNS);
                    txtUserIdDns.setText(mycode.CEK_USER_ID_DNS);
                    txtNoIzinDns.setText(mycode.CEK_NO_IZIN_DNS);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnDnsActionPerformed

    private void btnHpsDnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsDnsActionPerformed
        try {
            mycode.hapusDonasi(txtIdDonasi.getText());
            mycode.tampilDataDonasi(tabelDonasi, "SELECT*FROM Donasi");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsDnsActionPerformed

    private void txtCariDonasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDonasiKeyReleased
        String c = txtCariDonasi.getText();
        String cari = "SELECT*FROM Donasi WHERE ID_Donasi LIKE '%"+c+"%'"+
                      "OR Donasi_uang LIKE '%"+c+"%' OR Donasi_Barang LIKE '%"+c+"%'"+
                      "OR Donasi_Sembako LIKE '%"+c+"%' OR NIP LIKE '%"+c+"%'"+
                      "OR User_id LIKE '%"+c+"%' OR No_Izin LIKE '%"+c+"%'";
        mycode.tampilDataDonasi(tabelDonasi, cari);
    }//GEN-LAST:event_txtCariDonasiKeyReleased

    private void txtCariLSMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariLSMKeyReleased
        String c = txtCariLSM.getText();
        String cari = "SELECT*FROM LSM WHERE No_Izin LIKE '%"+c+"%'"+
                      "OR Nama_LSM LIKE '%"+c+"%' OR Alamat LIKE '%"+c+"%'"+
                      "OR User_IdL LIKE '%"+c+"%'"; // Password biasanya tidak dicari
        mycode.tampilDataLSM(tabelLSM, cari);
    }//GEN-LAST:event_txtCariLSMKeyReleased

    private void btnUbhLSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhLSMActionPerformed
       try {
            mycode.ubahLSM(txtNoIzin.getText(), txtNamaLSM.getText(), 
                           txtAlamatLSM.getText(), txtUserIdL.getText(), 
                           txtPasswordLSM.getText());
            mycode.tampilDataLSM(tabelLSM, "SELECT*FROM LSM");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhLSMActionPerformed

    private void btnSmpnLSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnLSMActionPerformed
        try {
            if(txtNoIzin.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Izin Belum Diisi");
                txtNoIzin.requestFocus();
            } else if(txtNamaLSM.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama LSM Belum Diisi");
                txtNamaLSM.requestFocus();
            } else if(txtAlamatLSM.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatLSM.requestFocus();
            } else if(txtUserIdL.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "User ID Belum Diisi");
                txtUserIdL.requestFocus();
            } else if(txtPasswordLSM.getText().isEmpty()){ // Asumsi JPasswordField: new String(txtPasswordLSM.getPassword())
                JOptionPane.showMessageDialog(null, "Password Belum Diisi");
                txtPasswordLSM.requestFocus();
            } else {
                mycode.simpanLSM02(txtNoIzin.getText(), txtNamaLSM.getText(), 
                                  txtAlamatLSM.getText(), txtUserIdL.getText(), 
                                  txtPasswordLSM.getText()); 

                mycode.tampilDataLSM(tabelLSM, "SELECT*FROM LSM");
                if (mycode.duplikasi == true){
                    txtNamaLSM.setText(mycode.CEK_NAMA_LSM);
                    txtAlamatLSM.setText(mycode.CEK_ALAMAT_LSM);
                    txtUserIdL.setText(mycode.CEK_USER_IDL);
                    txtPasswordLSM.setText(mycode.CEK_PASSWORD_LSM);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnLSMActionPerformed

    private void btnHpsLSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsLSMActionPerformed
        try {
            mycode.hapusLSM(txtNoIzin.getText());
            mycode.tampilDataLSM(tabelLSM, "SELECT*FROM LSM");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsLSMActionPerformed

    private void txtCariGlrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariGlrKeyReleased
        String c = txtCariGlr.getText();
        String cari = "SELECT*FROM Galeri WHERE Id_galeri LIKE '%"+c+"%'"+
                      "OR Foto LIKE '%"+c+"%' OR Keterangan LIKE '%"+c+"%'"+
                      "OR No_Izin LIKE '%"+c+"%'";
        mycode.tampilDataGaleri(tabelGaleri, cari);
    }//GEN-LAST:event_txtCariGlrKeyReleased

    private void btnHpsGlrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsGlrActionPerformed
        try {
            mycode.hapusGaleri(txtIdGaleri.getText());
            mycode.tampilDataGaleri(tabelGaleri, "SELECT*FROM Galeri");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsGlrActionPerformed

    private void btnSmpnGlrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnGlrActionPerformed
        try {
            if(txtIdGaleri.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Galeri Belum Diisi");
                txtIdGaleri.requestFocus();
            } else if(txtFoto.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Foto Belum Diisi");
                txtFoto.requestFocus();
            } else if(txtKeteranganGlr.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Keterangan Belum Diisi");
                txtKeteranganGlr.requestFocus();
            } else if(txtNoIzinGlr.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "No Izin Belum Diisi");
                txtNoIzinGlr.requestFocus();
            } else {
                mycode.simpanGaleri02(txtIdGaleri.getText(), txtFoto.getText(),
                                      txtKeteranganGlr.getText(), txtNoIzinGlr.getText());

                mycode.tampilDataGaleri(tabelGaleri, "SELECT*FROM Galeri");

                if (mycode.duplikasi == true){
                    txtFoto.setText(mycode.CEK_FOTO_GLR);
                    txtKeteranganGlr.setText(mycode.CEK_KETERANGAN_GLR);
                    txtNoIzinGlr.setText(mycode.CEK_NO_IZIN_GLR);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnGlrActionPerformed

    private void btnUbhGlrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhGlrActionPerformed
        try {
            mycode.ubahGaleri(txtIdGaleri.getText(), txtFoto.getText(),
                              txtKeteranganGlr.getText(), txtNoIzinGlr.getText());

            mycode.tampilDataGaleri(tabelGaleri, "SELECT*FROM Galeri");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhGlrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnDonasi;
    private javax.swing.JButton btnGalangDana;
    private javax.swing.JButton btnGaleri;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsDns;
    private javax.swing.JButton btnHpsGd;
    private javax.swing.JButton btnHpsGlr;
    private javax.swing.JButton btnHpsLSM;
    private javax.swing.JButton btnLsm;
    private javax.swing.JButton btnSmpnDns;
    private javax.swing.JButton btnSmpnGd;
    private javax.swing.JButton btnSmpnGlr;
    private javax.swing.JButton btnSmpnLSM;
    private javax.swing.JButton btnUbhDns;
    private javax.swing.JButton btnUbhGd;
    private javax.swing.JButton btnUbhGlr;
    private javax.swing.JButton btnUbhLSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlDonasi;
    private javax.swing.JPanel pnlGalangDana;
    private javax.swing.JPanel pnlGaleri;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLsm;
    private javax.swing.JTable tabelDonasi;
    private javax.swing.JTable tabelGalangDana;
    private javax.swing.JTable tabelGaleri;
    private javax.swing.JTable tabelLSM;
    private javax.swing.JTextField txtAlamatLSM;
    private javax.swing.JTextField txtCariDonasi;
    private javax.swing.JTextField txtCariGD;
    private javax.swing.JTextField txtCariGlr;
    private javax.swing.JTextField txtCariLSM;
    private javax.swing.JTextField txtDetailGD;
    private javax.swing.JTextField txtDonasiBarang;
    private javax.swing.JTextField txtDonasiSembako;
    private javax.swing.JTextField txtDonasiUang;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtFundraiserGD;
    private javax.swing.JTextField txtIdDonasi;
    private javax.swing.JTextField txtIdGalangDana;
    private javax.swing.JTextField txtIdGaleri;
    private javax.swing.JTextField txtKeteranganGlr;
    private javax.swing.JTextField txtNamaLSM;
    private javax.swing.JTextField txtNipDns;
    private javax.swing.JTextField txtNipGD;
    private javax.swing.JTextField txtNoIzin;
    private javax.swing.JTextField txtNoIzinDns;
    private javax.swing.JTextField txtNoIzinGD;
    private javax.swing.JTextField txtNoIzinGlr;
    private javax.swing.JTextField txtPasswordLSM;
    private javax.swing.JTextField txtUpdateInfoGD;
    private javax.swing.JTextField txtUserIdDns;
    private javax.swing.JTextField txtUserIdGD;
    private javax.swing.JTextField txtUserIdL;
    // End of variables declaration//GEN-END:variables
}
